language: java

# runs on default infrastructure (a container running Ubuntu 14.04)
sudo: enabled

addons:
  apt:
    sources:
    - sourceline: 'ppa:chris-lea/libsodium'
    packages:
    - libsodium-dev

script:
- mvn --batch-mode install
#- mvn --batch-mode org.pitest:pitest-maven:mutationCoverage

after_success:
- mvn javadoc:javadoc