version: 2
jobs:
  build:
    working_directory: ~/tessera
    environment:
      - MAVEN_OPTS: -Xmx512m
    docker:
      - image: maven:3.5-jdk-8

    steps:
      - checkout
  JaxbConfigFactoryTest
      - run:
          name: Create local repo
          command: mvn install dependency:resolve-plugins dependency:go-offline -DskipTests=true -Dmaven.javadoc.skip=true -Dchecksyle.skip=true -Dspotbugs.skip=true -Djacoco.skip=true -B -q
      - save_cache:
          paths:
          - ~/.m2
          key: tessera-{{ checksum "pom.xml" }}
      - run:
          name: Unit tests
          command: mvn clean install -pl \!tests/acceptance-test -B