version: 2.1
#jobs:
#  build:
#    working_directory: ~/tessera
#
#    docker:
#      - image: circleci/openjdk:8-jdk-browsers
#
#    steps:
#      - checkout
#      - run: mvn -v
dependencies:
  override:
    - mvn -DskipTests clean install dependency:resolve-plugins dependency:go-offline

test:
  override:
    - mvn -o surefire:test

