version: 2
jobs:
  build:
    working_directory: ~/tessera
    docker:
      - image: maven:3.5-jdk-8
    steps:
      - checkout
      - run:
          name: Create local repo
          command: mvn install dependency:resolve-plugins dependency:go-offline -DskipTests=true -Dmaven.javadoc.skip=true -Dchecksyle.skip=true -Dspotbugs.skip=true -Djacoco.skip=true -B
      - run:
          name: Unit tests
          command: mvn verify -pl !tests/acceptance-test -o -B