version: 2
jobs:
  build:
    
    working_directory: ~/tessera

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout

      - restore_cache:
          key: tessera-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: tessera-{{ checksum "pom.xml" }}
      
      - run: mvn install