name: Tessera CI Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
              java-version: 11
        - run: mvn package -Dsilent=true -DskipTests=true -Dmaven.javadoc.skip=true -Dchecksyle.skip=true -Dspotbugs.skip=true -Djacoco.skip=true -B dependency:go-offline
        - uses: actions/cache@v1
          with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-
        - uses: pioug/le-slack-message@v1.0.0
          if: failure()
          with:
            ACTION_NAME: Build and populate maven cache
            JOB: ${{ toJson(job) }}
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn install -pl \!tests/acceptance-test -P reduce-logging -o
      - uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          flags: unittests
          fail_ci_if_error: true
      - uses: pioug/le-slack-message@v1.0.0
        if: failure()
        with:
            ACTION_NAME: Run unit tests
            JOB: ${{ toJson(job) }}
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  gradleBuild:
        runs-on: ubuntu-latest
        needs: build
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-java@v1
            with:
              java-version: 11
          - uses: actions/cache@v1
            with:
              path: ~/.m2/repository
              key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
              restore-keys: |
                ${{ runner.os }}-maven-
          - run: ./gradlew build  -x :tests:acceptance-test:build -x dependencyCheckAnalyze -x javadoc
          
          - uses: pioug/le-slack-message@v1.0.0
            if: failure()
            with:
              ACTION_NAME: Run gradle build
              JOB: ${{ toJson(job) }}
              SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
            
  itest:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: 11
        - uses: actions/cache@v1
          with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-
        - run: mvn verify -pl tests/acceptance-test -P reduce-logging -o
        - uses: pioug/le-slack-message@v1.0.0
          if: failure()
          with:
            ACTION_NAME: Run integration tests
            JOB: ${{ toJson(job) }}
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  vaultTests:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: 11
        - uses: actions/cache@v1
          with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven-
        - run: |
            wget https://releases.hashicorp.com/vault/1.2.2/vault_1.2.2_linux_amd64.zip -O /tmp/vault_1.2.2_linux_amd64.zip
            mkdir -p vault/bin && pushd $_
            unzip /tmp/vault_1.2.2_linux_amd64.zip
            export PATH=$PATH:$PWD && popd
            mvn verify -pl tests/acceptance-test -P vault-acceptance-tests,reduce-logging -o
        - uses: pioug/le-slack-message@v1.0.0
          if: failure()
          with:
            ACTION_NAME: Run vault integration tests
            JOB: ${{ toJson(job) }}
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
  atest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: |
          export TESSERA_VERSION=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout`
          export TESSERA_JAR=~/.m2/repository/com/jpmorgan/quorum/tessera-app/$TESSERA_VERSION/tessera-app-$TESSERA_VERSION-app.jar
          cd
          git clone https://github.com/jpmorganchase/quorum-examples.git
          git clone https://github.com/jpmorganchase/quorum-acceptance-tests.git
          echo "Install geth"
          curl -L https://dl.bintray.com/quorumengineering/quorum/v2.5.0/geth_v2.5.0_linux_amd64.tar.gz -o geth.tar.gz
          tar xvzf geth.tar.gz
          sudo mv geth /usr/local/bin/
          geth version
          echo "Installed geth"
          echo "Install solc"
          curl -L https://github.com/ethereum/solidity/releases/download/v0.5.4/solc-static-linux -o solc
          sudo mv solc /usr/local/bin/
          sudo chmod 755 /usr/local/bin/solc
          solc --version
          echo "Installed solc"
          echo "Install gauge"
          curl -L https://github.com/getgauge/gauge/releases/download/v1.0.7/gauge-1.0.7-linux.x86_64.zip -o gauge.zip
          sudo unzip -o gauge.zip -d /usr/local/bin
          cd quorum-acceptance-tests
          gauge install
          cd
          echo "Installed gauge"
          echo "Start $TESSERA_JAR for 7 nodes"
          cd quorum-examples/examples/7nodes
          ./tessera-init.sh
          ./init.sh istanbul
          ./start.sh istanbul tessera
          cd ../../../
          echo "Started $TESSERA_JAR for 7 nodes"
          echo "Run quorum-acceptance-tests"
          cd quorum-acceptance-tests
          cp config/application-local.7nodes.yml config/application-local.yml
          mvn test
          echo "Complete quorum-acceptance-tests"
        env:
          MAVEN_OPTS: -Xms1024m -Xmx2048m
      - uses: pioug/le-slack-message@v1.0.0
        if: failure()
        with:
          ACTION_NAME: Run acceptance tests
          JOB: ${{ toJson(job) }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  slackNotification:
    runs-on: ubuntu-latest
    needs: [build,atest,itest,test,vaultTests]
    steps:
      - uses: pioug/le-slack-message@v1.0.0
        with:
          ACTION_NAME: Workflow success
          JOB: ${{ toJson(job) }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
